* Config/Preamble :noexport:
** LaTeX Config
#+BEGIN_SRC emacs-lisp :exports none  :results none :eval always
(setq org-latex-logfiles-extensions (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out" "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk" "blg" "brf" "fls" "entoc" "ps" "spl" "bbl" "xmpi" "run.xml" "bcf")))
(add-to-list 'org-latex-classes
             '("altacv" "\\documentclass[10pt,a4paper,ragged2e,withhyper]{altacv}

% Change the page layout if you need to
\\geometry{left=1.25cm,right=1.25cm,top=1.5cm,bottom=1.5cm,columnsep=1.2cm}

% Use roboto and lato for fonts
\\renewcommand{\\familydefault}{\\sfdefault}

% Change the colours if you want to
\\definecolor{SlateGrey}{HTML}{2E2E2E}
\\definecolor{LightGrey}{HTML}{666666}
\\definecolor{DarkPastelRed}{HTML}{450808}
\\definecolor{PastelRed}{HTML}{8F0D0D}
\\definecolor{GoldenEarth}{HTML}{E7D192}
\\colorlet{name}{black}
\\colorlet{tagline}{PastelRed}
\\colorlet{heading}{DarkPastelRed}
\\colorlet{headingrule}{GoldenEarth}
\\colorlet{subheading}{PastelRed}
\\colorlet{accent}{PastelRed}
\\colorlet{emphasis}{SlateGrey}
\\colorlet{body}{LightGrey}

% Change some fonts, if necessary
\\renewcommand{\\namefont}{\\Huge\\rmfamily\\bfseries}
\\renewcommand{\\personalinfofont}{\\footnotesize}
\\renewcommand{\\cvsectionfont}{\\LARGE\\rmfamily\\bfseries}
\\renewcommand{\\cvsubsectionfont}{\\large\\bfseries}

% Change the bullets for itemize and rating marker
% for \cvskill if you want to
\\renewcommand{\\itemmarker}{{\\small\\textbullet}}
\\renewcommand{\\ratingmarker}{\\faCircle}
"

               ("\\cvsection{%s}" . "\\cvsection*{%s}")
               ("\\cvevent{%s}" . "\\cvevent*{%s}")))
(setq org-latex-packages-alist 'nil)
(setq org-latex-default-packages-alist
      '(("rm" "roboto"  t)
        ("defaultsans" "lato" t)
        ("" "paracol" t)
        ))
#+END_SRC
#+LATEX_CLASS: altacv
#+LATEX_HEADER: \columnratio{0.6} % Set the left/right column width ratio to 6:4.
#+LATEX_HEADER: \usepackage[bottom]{footmisc}
#+LATEX_HEADER: \usepackage[spanish, activeacute]{babel}
** Exporter Settings
#+AUTHOR: Carlos Eduardo Martínez Aguilar
#+EXPORT_FILE_NAME: ./curriculum-vitae.pdf
#+OPTIONS: toc:nil title:nil H:1

** Macros
#+MACRO: cvevent \cvevent{$1}{$2}{$3}{$4}
#+MACRO: cvachievement \cvachievement{$1}{$2}{$3}{$4}
#+MACRO: cvtag \cvtag{$1}
#+MACRO: divider \divider
#+MACRO: par-div \par\divider
#+MACRO: new-page \newpage
* Curriculum Vitae
#+begin_export latex
\name{Carlos Eduardo Martínez Aguilar}
\photoR{2.8cm}{photo_2020-02-05_23-29-44.jpg}
\tagline{PhD Researcher}
#+end_export

#+begin_export latex
\personalinfo{
  %\homepage{www.aidanscannell.com}
  \email{cmartineza@ciencias.unam.mx}
  \phone{+52 5527200857}
  \location{CDMX, MX}
  \github{buddharta}
  %\linkedin{aidan-scannell-82522789/}
  \dob{14 de Julio 1992}
}
\makecvheader
#+end_export


* Educación y Experiencia
#+begin_export latex
\begin{paracol}{2}
#+end_export
#+begin_export latex
 \begin{quote}
 Soy un estudiante de doctorado en matemáticas interesado en sistemas dinámicos holomorfos y sus conexiones con análisis complejo y geometría compleja además de los aspectos computacionales de dichas teorías y la matemática en general. Actualmente me encuentro bajo la tutela del doctor Alberto Verjovsky Solá.
 \end{quote}
#+end_export

#+begin_export latex
 \cvsubsection{Experiencia}
#+end_export
{{{cvevent(Estudiante de doctorado y asistente de investigador, UNAM, Agosto 2020 -- Presente, CDMX-Cuernavaca\, MX)}}}

Me ecuentro investigando las relaciones entre el análisis complejo clásico y la teoría de variedades analíticas, específicamente en el caso que dichas variedades analíticas sean hojas de foliaciones en variedades holomorfas complejas compactas y en la mayor parte de los casos Kähler.

{{{cvtag(Geometría compleja)}}}
{{{cvtag(Análisis complejo)}}}
{{{cvtag(Sistemas dinámicos)}}}
{{{cvtag(Foliaciones)}}}
{{{cvtag(Geometría Kähler)}}}
# {{{cvtag(Model-based reinforcement learning)}}}

{{{par-div}}}
{{{cvevent(Asistente de profesor, UNAM, Sept 2015 -- presente, CDMX\, MX)}}}

Además de mis estudios en matemáticas he impartido las siguientes clases como asistente de profesor en licenciatura y posgrado
   - Análisis funcional (IIMAS - Posgrado).
   - Álgebra Superior I (Facultad de ciencias - Licenciatura).
   - Álgebra Superior II (Facultad de ciencias - Licenciatura).
   - Variable Compleja I (Facultad de ciencias - Licenciatura).
   - Ecuaciones Diferenciales Ordinarias I (Facultad de ciencias - Licenciatura).

{{{cvtag(Comunicación)}}}
{{{cvtag(Enseñanza)}}}



{{{divider}}}
#+begin_export latex
 \cvsection{Actividades Académicas}
#+end_export

#+begin_export latex
 \cvsubsection{Publicaciones}
#+end_export
#+begin_export latex
 \cvsubsubsection{Artículos}
#+end_export
     - [[https://arxiv.org/abs/2111.04846][Errett Bishop theorems on Complex Analytic Sets: Chow's Theorem Revisited, and Foliations of Compact Leaves on Kähler Manifolds (arxiv)]]

{{{divider}}}
#+begin_export latex
 \cvsubsection{Talleres Escuelas y Seminarios}
#+end_export

{{{cvevent(Escuela de Nudos y 3-variedades. Guanajuato, Guanajuato. Centro de Investigación en Matemáticas A.C., Diciembre de 2014\, MX)}}}

{{{par-div}}}

{{{cvevent(Encuentro de Geometría Algebraica. Guanajuato, Guanajuato. Centro de Investigación en Matemáticas A.C., Mayo de 2015\, MX)}}}

{{{par-div}}}

{{{cvevent(XIII Escuela de Verano en Matemáticas. Unidad Cuernavaca del Instituto de Matemáticas, UNAM, Julio de 2016.\, MX)}}}

{{{par-div}}}

{{{cvevent(Workshop on Kleinian groups and related topics.  Unidad Cuernavaca del Instituto de Matemáticas, UNAM, Agosto de 2016.\, MX)}}}

#+begin_export latex
 \cvsubsection{Certificados y diplomas}
#+end_export

{{{cvevent(Introduction to Programming with MATLAB, Vanderbilt University, Octubre 2020)}}}

{{{par-div}}}

{{{cvevent(Programación en Python, Pilares CDMX, Diciembre 2023)}}}
# ** Invited Talks :noexport:
# *** Geometry Talk :ignore:
# {{{cvevent(Synergising Bayesian Inference and Probabilistic Geometries for Robotic Control, Cognitive Systems - Technical University of Denmark (DTU), 18 March 2021, Zoom)}}}
# # - Presented a method for controlling multimodal dynamical systems synergising Bayesian inference and probabilistic geometries.
# - Presented a method synergising Bayesian inference and probabilistic geometries to control multimodal dynamical systems.
#
# {{{cvtag(Communication)}}}
# {{{cvtag(Probabilistic geometries)}}}
# {{{cvtag(Gaussian processes)}}}

# Switch to the right column - will automatically move to the next page.
#+begin_export latex
\switchcolumn
#+end_export

#+begin_export latex
 \cvsubsection{Habilidades y tecnologías}
#+end_export
{{{cvtag(Python)}}}
{{{cvtag(TensorFlow)}}}
{{{cvtag(SymPy)}}}
{{{cvtag(NumPy)}}}
{{{cvtag(SciPy)}}}
{{{cvtag(Matplotlib)}}}

{{{divider}}}

{{{cvtag(Java)}}}
{{{cvtag(C y C++)}}}
{{{cvtag(MATLAB)}}}
{{{cvtag(Haskell)}}}

{{{divider}}}

{{{cvtag(GNU/Linux)}}}
{{{cvtag(Git/GitHub)}}}
{{{cvtag(LaTeX)}}}
{{{cvtag(Org-mode)}}}
{{{cvtag(HTML/CSS)}}}

{{{divider}}}

#+begin_export latex
 \cvsubsection{Educación}
#+end_export

{{{cvevent(Doctorado en Ciencias Matemáticas. Instituto de Matemáticas, UNAM, CDMX, Agosto 2020 - Presente,)}}}
- Título de tesis: Un estudio de Foliaciones Holomorfas en Variedades Kahler compactas.
- Tutor: Alberto Verjovsky Santiago.

{{{divider}}}

{{{cvevent(Maestrtía en Ciencias Matemáticas. Instituto de Matemáticas, UNAM, CDMX, Agosto 2016 - Marzo 2019,)}}}
- Título de tesis: Estructuras proyectivas con holonomía fuchsiana.
- Tutores: Adolfo Guillot Santiago y Antonio Lascurain Orive.

{{{divider}}}

{{{cvevent( Licenciatura en Matemáticas (con mención honorífica), Facultad de Ciencias, UNAM, CDMX, Agosto 2011 - Sept 2016,)}}}
- Título de tesis: Restricciones universales para grupos fuchsianos.
- Asesor: Antonio Lascurain Orive.

{{{divider}}}

#+begin_export latex
\vspace{1cm}
\cvsubsection{Becas}
#+end_export
   - 2016-2018: Beca Nacional para Maestría en Ciencias Matemáticas - Consejo Nacional de Ciencia y Tecnología (CONACyT).
   - 2020-2024: Beca Nacional para Doctorado en Ciencias Matemáticas - Consejo Nacional de Ciencia y Tecnología (CONACyT).

#+begin_export latex
 \cvsubsection{Premios}
#+end_export
   {{{cvachievement(\faTrophy,Medalla Gabino Barreda, Universidad Nacional Autónoma de México (UNAM), Ciudad de México, México, 2017.Otorgada por ser el mejor de la generación 2012-2016 en matemáticas (obteniendo la calificación más alta de la generación)}}}

#+begin_export latex
 \cvsubsection{Idiomas}
#+end_export
   - Español, nativo
   - Inglés, fluido (Puntuación TOEFL iBT: 96)
   - Francés, intermedio
   - Japonés, básico


#+begin_export latex
\end{paracol}
\end{document}
#+end_export
